version: 0.1.{build}

install: 
  - cinst autoit.commandline

build: off

before_test:
  - aut2exe /in AutoItAppveyor.au3 /out AutoItAppveyor.exe /console

test_script: 
  - autoit3 /AutoIt3ExecuteScript AutoItAppveyor.au3