Run('appveyor AddMessage "test message"')
Run('appveyor AddTest "Test Passed" -Outcome Passed -Duration 10')
Run('appveyor AddTest "Test Failed" -Outcome Failed -Duration 10')
Run('appveyor AddTest "Test Framework" -Outcome Passed -Duration 10 -Framework "Micro"')
Run('appveyor AddTest "Test long" -Outcome Passed -Duration 10000')